CREATE TABLE ITEMS (
    ITEM_ID INT IDENTITY PRIMARY KEY,
    ITEM_NAME VARCHAR(255)
);

CREATE TABLE SUBITEMS (
    SUBITEM_ID INT IDENTITY PRIMARY KEY,
    ITEM_NAME VARCHAR(255),
    SUBITEM_NAME VARCHAR(255),
    ACTIVITY VARCHAR(255),
    WORK_DATE DATE
);
